//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admin_SMUniversityEntities : DbContext
    {
        public admin_SMUniversityEntities()
            : base("name=admin_SMUniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblArea> TblAreas { get; set; }
        public virtual DbSet<TblAttendance> TblAttendances { get; set; }
        public virtual DbSet<TblBalanceTransaction> TblBalanceTransactions { get; set; }
        public virtual DbSet<TblBranch> TblBranches { get; set; }
        public virtual DbSet<TblCardCategory> TblCardCategories { get; set; }
        public virtual DbSet<TblChargeCard> TblChargeCards { get; set; }
        public virtual DbSet<TblCollege> TblColleges { get; set; }
        public virtual DbSet<TblContactUsMsg> TblContactUsMsgs { get; set; }
        public virtual DbSet<TblEmployee> TblEmployees { get; set; }
        public virtual DbSet<TblEvaluation> TblEvaluations { get; set; }
        public virtual DbSet<TblEvaluationQuestion> TblEvaluationQuestions { get; set; }
        public virtual DbSet<TblEvaluationQuestionAnswer> TblEvaluationQuestionAnswers { get; set; }
        public virtual DbSet<TblFavoriteSession> TblFavoriteSessions { get; set; }
        public virtual DbSet<TblGovernorate> TblGovernorates { get; set; }
        public virtual DbSet<TblHall> TblHalls { get; set; }
        public virtual DbSet<TblHelpQuestion> TblHelpQuestions { get; set; }
        public virtual DbSet<TblInstitute> TblInstitutes { get; set; }
        public virtual DbSet<TblInvoice> TblInvoices { get; set; }
        public virtual DbSet<TblLecturer> TblLecturers { get; set; }
        public virtual DbSet<TblLecturerPaymentMethod> TblLecturerPaymentMethods { get; set; }
        public virtual DbSet<TblLecturerSubject> TblLecturerSubjects { get; set; }
        public virtual DbSet<TblMajor> TblMajors { get; set; }
        public virtual DbSet<TblManualInvoice> TblManualInvoices { get; set; }
        public virtual DbSet<TblNotification> TblNotifications { get; set; }
        public virtual DbSet<TblPermission> TblPermissions { get; set; }
        public virtual DbSet<TblPermissionCategory> TblPermissionCategories { get; set; }
        public virtual DbSet<TblPermissionUser> TblPermissionUsers { get; set; }
        public virtual DbSet<TblPrivateSession> TblPrivateSessions { get; set; }
        public virtual DbSet<TblProduct> TblProducts { get; set; }
        public virtual DbSet<TblProductCategory> TblProductCategories { get; set; }
        public virtual DbSet<TblRevenue> TblRevenues { get; set; }
        public virtual DbSet<TblScreen> TblScreens { get; set; }
        public virtual DbSet<TblScreenHall> TblScreenHalls { get; set; }
        public virtual DbSet<TblSession> TblSessions { get; set; }
        public virtual DbSet<TblSessionDetail> TblSessionDetails { get; set; }
        public virtual DbSet<TblSessionPricing> TblSessionPricings { get; set; }
        public virtual DbSet<TblSessionTime> TblSessionTimes { get; set; }
        public virtual DbSet<TblStudent> TblStudents { get; set; }
        public virtual DbSet<TblStudentComplaint> TblStudentComplaints { get; set; }
        public virtual DbSet<TblSubject> TblSubjects { get; set; }
        public virtual DbSet<TblSubscription> TblSubscriptions { get; set; }
        public virtual DbSet<TblUniversity> TblUniversities { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblUserCategory> TblUserCategories { get; set; }
        public virtual DbSet<TblUserCredential> TblUserCredentials { get; set; }
        public virtual DbSet<TblUserType> TblUserTypes { get; set; }
        public virtual DbSet<TblVoucher> TblVouchers { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<TblRegisterDevice> TblRegisterDevices { get; set; }
    }
}
