//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAttendance
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public byte Attend { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int SubscriptionID { get; set; }
        public int SessionTimesID { get; set; }
    
        public virtual TblSessionTime TblSessionTime { get; set; }
        public virtual TblSessionTime TblSessionTime1 { get; set; }
        public virtual TblSessionTime TblSessionTime2 { get; set; }
        public virtual TblStudent TblStudent { get; set; }
        public virtual TblStudent TblStudent1 { get; set; }
        public virtual TblStudent TblStudent2 { get; set; }
        public virtual TblStudent TblStudent3 { get; set; }
        public virtual TblStudent TblStudent4 { get; set; }
        public virtual TblStudent TblStudent5 { get; set; }
        public virtual TblSubscription TblSubscription { get; set; }
        public virtual TblSubscription TblSubscription1 { get; set; }
        public virtual TblSubscription TblSubscription2 { get; set; }
    }
}
