//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBalanceTransaction
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TitleAr { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int TransactionTypeID { get; set; }
        public bool Pending { get; set; }
        public string PaymentMethod { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string TitleEn { get; set; }
    
        public virtual TblStudent TblStudent { get; set; }
        public virtual TblStudent TblStudent1 { get; set; }
        public virtual TblStudent TblStudent2 { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual TransactionType TransactionType1 { get; set; }
        public virtual TransactionType TransactionType2 { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
