//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCollege
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCollege()
        {
            this.TblMajors = new HashSet<TblMajor>();
            this.TblMajors1 = new HashSet<TblMajor>();
            this.TblMajors2 = new HashSet<TblMajor>();
            this.TblMajors3 = new HashSet<TblMajor>();
            this.TblMajors4 = new HashSet<TblMajor>();
            this.TblMajors5 = new HashSet<TblMajor>();
            this.TblStudents = new HashSet<TblStudent>();
            this.TblStudents1 = new HashSet<TblStudent>();
            this.TblStudents2 = new HashSet<TblStudent>();
            this.TblStudents3 = new HashSet<TblStudent>();
            this.TblStudents4 = new HashSet<TblStudent>();
            this.TblStudents5 = new HashSet<TblStudent>();
        }
    
        public int ID { get; set; }
        public string NameAr { get; set; }
        public int UniversityID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string NameEn { get; set; }
    
        public virtual TblUniversity TblUniversity { get; set; }
        public virtual TblUniversity TblUniversity1 { get; set; }
        public virtual TblUniversity TblUniversity2 { get; set; }
        public virtual TblUniversity TblUniversity3 { get; set; }
        public virtual TblUniversity TblUniversity4 { get; set; }
        public virtual TblUniversity TblUniversity5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMajor> TblMajors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMajor> TblMajors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMajor> TblMajors2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMajor> TblMajors3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMajor> TblMajors4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMajor> TblMajors5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudent> TblStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudent> TblStudents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudent> TblStudents2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudent> TblStudents3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudent> TblStudents4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudent> TblStudents5 { get; set; }
    }
}
