//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEvaluation
    {
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public int AnswerID { get; set; }
        public int StudentID { get; set; }
        public int SessionID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string EvaluationNotes { get; set; }
    
        public virtual TblEvaluationQuestionAnswer TblEvaluationQuestionAnswer { get; set; }
        public virtual TblEvaluationQuestion TblEvaluationQuestion { get; set; }
        public virtual TblSession TblSession { get; set; }
        public virtual TblStudent TblStudent { get; set; }
    }
}
