//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInvoice
    {
        public int ID { get; set; }
        public long Serial { get; set; }
        public int SubscriptionID { get; set; }
        public int EmployeeID { get; set; }
        public bool Pending { get; set; }
        public string PaymentMethod { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual TblEmployee TblEmployee { get; set; }
        public virtual TblSubscription TblSubscription { get; set; }
    }
}
