//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotification
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> LecturerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TitleAr { get; set; }
        public string DescriptionAr { get; set; }
        public string Picture { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string TitleEn { get; set; }
        public string DescriptionEn { get; set; }
        public bool Type { get; set; }
    
        public virtual TblLecturer TblLecturer { get; set; }
        public virtual TblStudent TblStudent { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
