//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrivateSession
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int SubjectID { get; set; }
        public int LecturerID { get; set; }
        public string RequestMsg { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public bool IsCourse { get; set; }
    
        public virtual TblLecturer TblLecturer { get; set; }
        public virtual TblStudent TblStudent { get; set; }
        public virtual TblSubject TblSubject { get; set; }
    }
}
