//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRevenue
    {
        public int ID { get; set; }
        public string RevenueTypeAr { get; set; }
        public decimal Value { get; set; }
        public int TeacherID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public string RevenueTypeEn { get; set; }
    
        public virtual TblLecturer TblLecturer { get; set; }
        public virtual TblLecturer TblLecturer1 { get; set; }
        public virtual TblLecturer TblLecturer2 { get; set; }
        public virtual TblLecturer TblLecturer3 { get; set; }
        public virtual TblLecturer TblLecturer4 { get; set; }
        public virtual TblLecturer TblLecturer5 { get; set; }
    }
}
