//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSubject()
        {
            this.TblLecturerSubjects = new HashSet<TblLecturerSubject>();
            this.TblPrivateSessions = new HashSet<TblPrivateSession>();
            this.TblSessions = new HashSet<TblSession>();
            this.TblSessions1 = new HashSet<TblSession>();
            this.TblSessions2 = new HashSet<TblSession>();
            this.TblSessions3 = new HashSet<TblSession>();
            this.TblSessions4 = new HashSet<TblSession>();
            this.TblSessions5 = new HashSet<TblSession>();
        }
    
        public int ID { get; set; }
        public int MajorID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLecturerSubject> TblLecturerSubjects { get; set; }
        public virtual TblMajor TblMajor { get; set; }
        public virtual TblMajor TblMajor1 { get; set; }
        public virtual TblMajor TblMajor2 { get; set; }
        public virtual TblMajor TblMajor3 { get; set; }
        public virtual TblMajor TblMajor4 { get; set; }
        public virtual TblMajor TblMajor5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPrivateSession> TblPrivateSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSession> TblSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSession> TblSessions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSession> TblSessions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSession> TblSessions3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSession> TblSessions4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSession> TblSessions5 { get; set; }
    }
}
