//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblStudent()
        {
            this.TblAttendances = new HashSet<TblAttendance>();
            this.TblAttendances1 = new HashSet<TblAttendance>();
            this.TblAttendances2 = new HashSet<TblAttendance>();
            this.TblAttendances3 = new HashSet<TblAttendance>();
            this.TblAttendances4 = new HashSet<TblAttendance>();
            this.TblAttendances5 = new HashSet<TblAttendance>();
            this.TblBalanceTransactions = new HashSet<TblBalanceTransaction>();
            this.TblBalanceTransactions1 = new HashSet<TblBalanceTransaction>();
            this.TblBalanceTransactions2 = new HashSet<TblBalanceTransaction>();
            this.TblContactUsMsgs = new HashSet<TblContactUsMsg>();
            this.TblEvaluations = new HashSet<TblEvaluation>();
            this.TblFavoriteSessions = new HashSet<TblFavoriteSession>();
            this.TblFavoriteSessions1 = new HashSet<TblFavoriteSession>();
            this.TblFavoriteSessions2 = new HashSet<TblFavoriteSession>();
            this.TblNotifications = new HashSet<TblNotification>();
            this.TblPrivateSessions = new HashSet<TblPrivateSession>();
            this.TblStudentComplaints = new HashSet<TblStudentComplaint>();
            this.TblSubscriptions = new HashSet<TblSubscription>();
            this.TblSubscriptions1 = new HashSet<TblSubscription>();
            this.TblSubscriptions2 = new HashSet<TblSubscription>();
            this.TblSubscriptions3 = new HashSet<TblSubscription>();
            this.TblSubscriptions4 = new HashSet<TblSubscription>();
            this.TblSubscriptions5 = new HashSet<TblSubscription>();
            this.TblRegisterDevices = new HashSet<TblRegisterDevice>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string ThirdName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> GovernorateID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string ProfilePic { get; set; }
        public decimal Balance { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> CollegeID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> MajorID { get; set; }
        public Nullable<int> CredentialsID { get; set; }
        public string VerificationCode { get; set; }
        public bool Verified { get; set; }
        public Nullable<bool> StudentType { get; set; }
    
        public virtual TblArea TblArea { get; set; }
        public virtual TblArea TblArea1 { get; set; }
        public virtual TblArea TblArea2 { get; set; }
        public virtual TblArea TblArea3 { get; set; }
        public virtual TblArea TblArea4 { get; set; }
        public virtual TblArea TblArea5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBalanceTransaction> TblBalanceTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBalanceTransaction> TblBalanceTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBalanceTransaction> TblBalanceTransactions2 { get; set; }
        public virtual TblBranch TblBranch { get; set; }
        public virtual TblBranch TblBranch1 { get; set; }
        public virtual TblBranch TblBranch2 { get; set; }
        public virtual TblBranch TblBranch3 { get; set; }
        public virtual TblBranch TblBranch4 { get; set; }
        public virtual TblBranch TblBranch5 { get; set; }
        public virtual TblCollege TblCollege { get; set; }
        public virtual TblCollege TblCollege1 { get; set; }
        public virtual TblCollege TblCollege2 { get; set; }
        public virtual TblCollege TblCollege3 { get; set; }
        public virtual TblCollege TblCollege4 { get; set; }
        public virtual TblCollege TblCollege5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblContactUsMsg> TblContactUsMsgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEvaluation> TblEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavoriteSession> TblFavoriteSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavoriteSession> TblFavoriteSessions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavoriteSession> TblFavoriteSessions2 { get; set; }
        public virtual TblGovernorate TblGovernorate { get; set; }
        public virtual TblGovernorate TblGovernorate1 { get; set; }
        public virtual TblGovernorate TblGovernorate2 { get; set; }
        public virtual TblGovernorate TblGovernorate3 { get; set; }
        public virtual TblGovernorate TblGovernorate4 { get; set; }
        public virtual TblGovernorate TblGovernorate5 { get; set; }
        public virtual TblMajor TblMajor { get; set; }
        public virtual TblMajor TblMajor1 { get; set; }
        public virtual TblMajor TblMajor2 { get; set; }
        public virtual TblMajor TblMajor3 { get; set; }
        public virtual TblMajor TblMajor4 { get; set; }
        public virtual TblMajor TblMajor5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblNotification> TblNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPrivateSession> TblPrivateSessions { get; set; }
        public virtual TblUserCredential TblUserCredential { get; set; }
        public virtual TblUserCredential TblUserCredential1 { get; set; }
        public virtual TblUserCredential TblUserCredential2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblStudentComplaint> TblStudentComplaints { get; set; }
        public virtual TblUniversity TblUniversity { get; set; }
        public virtual TblUniversity TblUniversity1 { get; set; }
        public virtual TblUniversity TblUniversity2 { get; set; }
        public virtual TblUniversity TblUniversity3 { get; set; }
        public virtual TblUniversity TblUniversity4 { get; set; }
        public virtual TblUniversity TblUniversity5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRegisterDevice> TblRegisterDevices { get; set; }
    }
}
