//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSession()
        {
            this.TblEvaluations = new HashSet<TblEvaluation>();
            this.TblFavoriteSessions = new HashSet<TblFavoriteSession>();
            this.TblFavoriteSessions1 = new HashSet<TblFavoriteSession>();
            this.TblFavoriteSessions2 = new HashSet<TblFavoriteSession>();
            this.TblSessionTimes = new HashSet<TblSessionTime>();
            this.TblSessionDetails = new HashSet<TblSessionDetail>();
            this.TblSessionDetails1 = new HashSet<TblSessionDetail>();
            this.TblSessionTimes1 = new HashSet<TblSessionTime>();
            this.TblSessionDetails2 = new HashSet<TblSessionDetail>();
            this.TblSessionPricings = new HashSet<TblSessionPricing>();
            this.TblSessionDetails3 = new HashSet<TblSessionDetail>();
            this.TblSessionDetails4 = new HashSet<TblSessionDetail>();
            this.TblSessionTimes2 = new HashSet<TblSessionTime>();
            this.TblSessionDetails5 = new HashSet<TblSessionDetail>();
            this.TblSubscriptions = new HashSet<TblSubscription>();
            this.TblSubscriptions1 = new HashSet<TblSubscription>();
            this.TblSubscriptions2 = new HashSet<TblSubscription>();
            this.TblSubscriptions3 = new HashSet<TblSubscription>();
            this.TblSubscriptions4 = new HashSet<TblSubscription>();
            this.TblSubscriptions5 = new HashSet<TblSubscription>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public int LecturerID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Description { get; set; }
        public bool Type { get; set; }
        public int LecturesCount { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int HallID { get; set; }
        public string Name { get; set; }
        public byte LecturerAccountMethod { get; set; }
        public string SessionCode { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public string NameEn { get; set; }
        public Nullable<bool> ForPublic { get; set; }
        public string DescriptionEn { get; set; }
        public string Picture { get; set; }
    
        public virtual TblBranch TblBranch { get; set; }
        public virtual TblBranch TblBranch1 { get; set; }
        public virtual TblBranch TblBranch2 { get; set; }
        public virtual TblBranch TblBranch3 { get; set; }
        public virtual TblBranch TblBranch4 { get; set; }
        public virtual TblBranch TblBranch5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEvaluation> TblEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavoriteSession> TblFavoriteSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavoriteSession> TblFavoriteSessions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavoriteSession> TblFavoriteSessions2 { get; set; }
        public virtual TblHall TblHall { get; set; }
        public virtual TblHall TblHall1 { get; set; }
        public virtual TblHall TblHall2 { get; set; }
        public virtual TblLecturer TblLecturer { get; set; }
        public virtual TblLecturer TblLecturer1 { get; set; }
        public virtual TblLecturer TblLecturer2 { get; set; }
        public virtual TblLecturer TblLecturer3 { get; set; }
        public virtual TblLecturer TblLecturer4 { get; set; }
        public virtual TblLecturer TblLecturer5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionTime> TblSessionTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionDetail> TblSessionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionDetail> TblSessionDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionTime> TblSessionTimes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionDetail> TblSessionDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionPricing> TblSessionPricings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionDetail> TblSessionDetails3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionDetail> TblSessionDetails4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionTime> TblSessionTimes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSessionDetail> TblSessionDetails5 { get; set; }
        public virtual TblSubject TblSubject { get; set; }
        public virtual TblSubject TblSubject1 { get; set; }
        public virtual TblSubject TblSubject2 { get; set; }
        public virtual TblSubject TblSubject3 { get; set; }
        public virtual TblSubject TblSubject4 { get; set; }
        public virtual TblSubject TblSubject5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubscription> TblSubscriptions5 { get; set; }
    }
}
