//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudentComplaint
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int HelpQuestionID { get; set; }
        public string Complaint { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual TblHelpQuestion TblHelpQuestion { get; set; }
        public virtual TblStudent TblStudent { get; set; }
    }
}
