//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSubscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSubscription()
        {
            this.TblAttendances = new HashSet<TblAttendance>();
            this.TblAttendances1 = new HashSet<TblAttendance>();
            this.TblAttendances2 = new HashSet<TblAttendance>();
            this.TblInvoices = new HashSet<TblInvoice>();
        }
    
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int SessionID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool Ended { get; set; }
        public bool Pending { get; set; }
        public byte PriceType { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAttendance> TblAttendances2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInvoice> TblInvoices { get; set; }
        public virtual TblSession TblSession { get; set; }
        public virtual TblSession TblSession1 { get; set; }
        public virtual TblSession TblSession2 { get; set; }
        public virtual TblSession TblSession3 { get; set; }
        public virtual TblSession TblSession4 { get; set; }
        public virtual TblSession TblSession5 { get; set; }
        public virtual TblStudent TblStudent { get; set; }
        public virtual TblStudent TblStudent1 { get; set; }
        public virtual TblStudent TblStudent2 { get; set; }
        public virtual TblStudent TblStudent3 { get; set; }
        public virtual TblStudent TblStudent4 { get; set; }
        public virtual TblStudent TblStudent5 { get; set; }
    }
}
