//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSessionDetail
    {
        public int ID { get; set; }
        public string QRCode { get; set; }
        public string RevenueType { get; set; }
        public int SessionID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public decimal Cost { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
    
        public virtual TblSession TblSession { get; set; }
        public virtual TblSession TblSession1 { get; set; }
        public virtual TblSession TblSession2 { get; set; }
        public virtual TblSession TblSession3 { get; set; }
        public virtual TblSession TblSession4 { get; set; }
        public virtual TblSession TblSession5 { get; set; }
    }
}
