//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUser()
        {
            this.TblBalanceTransactions = new HashSet<TblBalanceTransaction>();
            this.TblNotifications = new HashSet<TblNotification>();
            this.TblPermissionUsers = new HashSet<TblPermissionUser>();
            this.TblVouchers = new HashSet<TblVoucher>();
        }
    
        public int ID { get; set; }
        public string NameAr { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int CredentialsID { get; set; }
        public int BranchID { get; set; }
        public int UserCategoryID { get; set; }
        public string ProfilePic { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string NameEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBalanceTransaction> TblBalanceTransactions { get; set; }
        public virtual TblBranch TblBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblNotification> TblNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPermissionUser> TblPermissionUsers { get; set; }
        public virtual TblUserCredential TblUserCredential { get; set; }
        public virtual TblUserCategory TblUserCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVoucher> TblVouchers { get; set; }
    }
}
