//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMUModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVoucher
    {
        public int ID { get; set; }
        public long Serial { get; set; }
        public Nullable<int> LecturerID { get; set; }
        public Nullable<int> HallID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Notes { get; set; }
        public decimal Cost { get; set; }
        public string PaymentMethod { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public bool Type { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual TblHall TblHall { get; set; }
        public virtual TblLecturer TblLecturer { get; set; }
        public virtual TblUser TblUser { get; set; }
        public virtual TblVoucherCategory TblVoucherCategory { get; set; }
    }
}
