//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.TapServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayRequestDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class PayRequestDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAPI.TapServiceReference.CustomerDC CustomerDCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAPI.TapServiceReference.MerMastDC MerMastDCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAPI.TapServiceReference.GateWayDC[] lstGateWayDCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAPI.TapServiceReference.MetaData[] lstMetaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAPI.TapServiceReference.ProductDC[] lstProductDCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAPI.TapServiceReference.CustomerDC CustomerDC {
            get {
                return this.CustomerDCField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDCField, value) != true)) {
                    this.CustomerDCField = value;
                    this.RaisePropertyChanged("CustomerDC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAPI.TapServiceReference.MerMastDC MerMastDC {
            get {
                return this.MerMastDCField;
            }
            set {
                if ((object.ReferenceEquals(this.MerMastDCField, value) != true)) {
                    this.MerMastDCField = value;
                    this.RaisePropertyChanged("MerMastDC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAPI.TapServiceReference.GateWayDC[] lstGateWayDC {
            get {
                return this.lstGateWayDCField;
            }
            set {
                if ((object.ReferenceEquals(this.lstGateWayDCField, value) != true)) {
                    this.lstGateWayDCField = value;
                    this.RaisePropertyChanged("lstGateWayDC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAPI.TapServiceReference.MetaData[] lstMetaData {
            get {
                return this.lstMetaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.lstMetaDataField, value) != true)) {
                    this.lstMetaDataField = value;
                    this.RaisePropertyChanged("lstMetaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAPI.TapServiceReference.ProductDC[] lstProductDC {
            get {
                return this.lstProductDCField;
            }
            set {
                if ((object.ReferenceEquals(this.lstProductDCField, value) != true)) {
                    this.lstProductDCField = value;
                    this.RaisePropertyChanged("lstProductDC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class CustomerDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CivilIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apartment {
            get {
                return this.ApartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartmentField, value) != true)) {
                    this.ApartmentField = value;
                    this.RaisePropertyChanged("Apartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avenue {
            get {
                return this.AvenueField;
            }
            set {
                if ((object.ReferenceEquals(this.AvenueField, value) != true)) {
                    this.AvenueField = value;
                    this.RaisePropertyChanged("Avenue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CivilID {
            get {
                return this.CivilIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CivilIDField, value) != true)) {
                    this.CivilIDField = value;
                    this.RaisePropertyChanged("CivilID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerMastDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class MerMastDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutoReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GatWayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LangCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MerchantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayPlatformField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoReturn {
            get {
                return this.AutoReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoReturnField, value) != true)) {
                    this.AutoReturnField = value;
                    this.RaisePropertyChanged("AutoReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorURL {
            get {
                return this.ErrorURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorURLField, value) != true)) {
                    this.ErrorURLField = value;
                    this.RaisePropertyChanged("ErrorURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GatWayID {
            get {
                return this.GatWayIDField;
            }
            set {
                if ((this.GatWayIDField.Equals(value) != true)) {
                    this.GatWayIDField = value;
                    this.RaisePropertyChanged("GatWayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashString {
            get {
                return this.HashStringField;
            }
            set {
                if ((object.ReferenceEquals(this.HashStringField, value) != true)) {
                    this.HashStringField = value;
                    this.RaisePropertyChanged("HashString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LangCode {
            get {
                return this.LangCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LangCodeField, value) != true)) {
                    this.LangCodeField = value;
                    this.RaisePropertyChanged("LangCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((this.MerchantIDField.Equals(value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayPlatform {
            get {
                return this.PayPlatformField;
            }
            set {
                if ((object.ReferenceEquals(this.PayPlatformField, value) != true)) {
                    this.PayPlatformField = value;
                    this.RaisePropertyChanged("PayPlatform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentAction {
            get {
                return this.PaymentActionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentActionField, value) != true)) {
                    this.PaymentActionField = value;
                    this.RaisePropertyChanged("PaymentAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostURL {
            get {
                return this.PostURLField;
            }
            set {
                if ((object.ReferenceEquals(this.PostURLField, value) != true)) {
                    this.PostURLField = value;
                    this.RaisePropertyChanged("PostURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnURL {
            get {
                return this.ReturnURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnURLField, value) != true)) {
                    this.ReturnURLField = value;
                    this.RaisePropertyChanged("ReturnURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GateWayDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class GateWayDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaData", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class MetaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class ProductDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VndIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgUrl {
            get {
                return this.ImgUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgUrlField, value) != true)) {
                    this.ImgUrlField = value;
                    this.RaisePropertyChanged("ImgUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitDesc {
            get {
                return this.UnitDescField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitDescField, value) != true)) {
                    this.UnitDescField = value;
                    this.RaisePropertyChanged("UnitDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitID {
            get {
                return this.UnitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitIDField, value) != true)) {
                    this.UnitIDField = value;
                    this.RaisePropertyChanged("UnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitName {
            get {
                return this.UnitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitNameField, value) != true)) {
                    this.UnitNameField = value;
                    this.RaisePropertyChanged("UnitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VndID {
            get {
                return this.VndIDField;
            }
            set {
                if ((object.ReferenceEquals(this.VndIDField, value) != true)) {
                    this.VndIDField = value;
                    this.RaisePropertyChanged("VndID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayResponseDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class PayResponseDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TapPayURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentURL {
            get {
                return this.PaymentURLField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentURLField, value) != true)) {
                    this.PaymentURLField = value;
                    this.RaisePropertyChanged("PaymentURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TapPayURL {
            get {
                return this.TapPayURLField;
            }
            set {
                if ((object.ReferenceEquals(this.TapPayURLField, value) != true)) {
                    this.TapPayURLField = value;
                    this.RaisePropertyChanged("TapPayURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderStatusRequestDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebAPI.TapServiceReference.CaptureRequestDC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebAPI.TapServiceReference.GetOrderRequestDC))]
    public partial class GetOrderStatusRequestDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MerchantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((this.MerchantIDField.Equals(value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureRequestDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class CaptureRequestDC : WebAPI.TapServiceReference.GetOrderStatusRequestDC {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderRequestDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class GetOrderRequestDC : WebAPI.TapServiceReference.GetOrderStatusRequestDC {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatusResponseDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebAPI.TapServiceReference.CaptureResponseDC))]
    public partial class OrderStatusResponseDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayTxnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayTxnID {
            get {
                return this.PayTxnIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayTxnIDField, value) != true)) {
                    this.PayTxnIDField = value;
                    this.RaisePropertyChanged("PayTxnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paymode {
            get {
                return this.PaymodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymodeField, value) != true)) {
                    this.PaymodeField = value;
                    this.RaisePropertyChanged("Paymode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackID {
            get {
                return this.TrackIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackIDField, value) != true)) {
                    this.TrackIDField = value;
                    this.RaisePropertyChanged("TrackID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureResponseDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class CaptureResponseDC : WebAPI.TapServiceReference.OrderStatusResponseDC {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResponseDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class OrderResponseDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAPI.TapServiceReference.OrderStatusResponseDC OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAPI.TapServiceReference.PayRequestDC PayRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAPI.TapServiceReference.OrderStatusResponseDC OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusField, value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAPI.TapServiceReference.PayRequestDC PayRequest {
            get {
                return this.PayRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.PayRequestField, value) != true)) {
                    this.PayRequestField = value;
                    this.RaisePropertyChanged("PayRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundRequestDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class RefundRequestDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IBANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MerchantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBAN {
            get {
                return this.IBANField;
            }
            set {
                if ((object.ReferenceEquals(this.IBANField, value) != true)) {
                    this.IBANField = value;
                    this.RaisePropertyChanged("IBAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((this.MerchantIDField.Equals(value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdID {
            get {
                return this.OrdIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdIDField, value) != true)) {
                    this.OrdIDField = value;
                    this.RaisePropertyChanged("OrdID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefundResponseDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class RefundResponseDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRefundStatusRequestDC", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class GetRefundStatusRequestDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MerchantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((this.MerchantIDField.Equals(value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transactions_Request", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class Transactions_Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long merchantidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string starting_afterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int toField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int from {
            get {
                return this.fromField;
            }
            set {
                if ((this.fromField.Equals(value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long merchantid {
            get {
                return this.merchantidField;
            }
            set {
                if ((this.merchantidField.Equals(value) != true)) {
                    this.merchantidField = value;
                    this.RaisePropertyChanged("merchantid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string starting_after {
            get {
                return this.starting_afterField;
            }
            set {
                if ((object.ReferenceEquals(this.starting_afterField, value) != true)) {
                    this.starting_afterField = value;
                    this.RaisePropertyChanged("starting_after");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int to {
            get {
                return this.toField;
            }
            set {
                if ((this.toField.Equals(value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transactions_Response", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class Transactions_Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool has_rowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAPI.TapServiceReference.Transaction[] transactionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool has_rows {
            get {
                return this.has_rowsField;
            }
            set {
                if ((this.has_rowsField.Equals(value) != true)) {
                    this.has_rowsField = value;
                    this.RaisePropertyChanged("has_rows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAPI.TapServiceReference.Transaction[] transactions {
            get {
                return this.transactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionsField, value) != true)) {
                    this.transactionsField = value;
                    this.RaisePropertyChanged("transactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/Tap.PayServiceContract")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string card_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_referenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_methodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long rowidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tap_referenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string card_number {
            get {
                return this.card_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.card_numberField, value) != true)) {
                    this.card_numberField = value;
                    this.RaisePropertyChanged("card_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyField, value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime datetime {
            get {
                return this.datetimeField;
            }
            set {
                if ((this.datetimeField.Equals(value) != true)) {
                    this.datetimeField = value;
                    this.RaisePropertyChanged("datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchant_reference {
            get {
                return this.merchant_referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_referenceField, value) != true)) {
                    this.merchant_referenceField = value;
                    this.RaisePropertyChanged("merchant_reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_id {
            get {
                return this.payment_idField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_idField, value) != true)) {
                    this.payment_idField = value;
                    this.RaisePropertyChanged("payment_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string payment_method {
            get {
                return this.payment_methodField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_methodField, value) != true)) {
                    this.payment_methodField = value;
                    this.RaisePropertyChanged("payment_method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long rowid {
            get {
                return this.rowidField;
            }
            set {
                if ((this.rowidField.Equals(value) != true)) {
                    this.rowidField = value;
                    this.RaisePropertyChanged("rowid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tap_reference {
            get {
                return this.tap_referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.tap_referenceField, value) != true)) {
                    this.tap_referenceField = value;
                    this.RaisePropertyChanged("tap_reference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TapServiceReference.IPayGatewayService")]
    public interface IPayGatewayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/PaymentRequest", ReplyAction="http://tempuri.org/IPayGatewayService/PaymentRequestResponse")]
        WebAPI.TapServiceReference.PayResponseDC PaymentRequest(WebAPI.TapServiceReference.PayRequestDC PayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/PaymentRequest", ReplyAction="http://tempuri.org/IPayGatewayService/PaymentRequestResponse")]
        System.Threading.Tasks.Task<WebAPI.TapServiceReference.PayResponseDC> PaymentRequestAsync(WebAPI.TapServiceReference.PayRequestDC PayRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetOrderStatusRequest", ReplyAction="http://tempuri.org/IPayGatewayService/GetOrderStatusRequestResponse")]
        WebAPI.TapServiceReference.OrderStatusResponseDC GetOrderStatusRequest(WebAPI.TapServiceReference.GetOrderStatusRequestDC OrderStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetOrderStatusRequest", ReplyAction="http://tempuri.org/IPayGatewayService/GetOrderStatusRequestResponse")]
        System.Threading.Tasks.Task<WebAPI.TapServiceReference.OrderStatusResponseDC> GetOrderStatusRequestAsync(WebAPI.TapServiceReference.GetOrderStatusRequestDC OrderStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetOrderStatusRequestbyMerchantID", ReplyAction="http://tempuri.org/IPayGatewayService/GetOrderStatusRequestbyMerchantIDResponse")]
        WebAPI.TapServiceReference.OrderStatusResponseDC GetOrderStatusRequestbyMerchantID(WebAPI.TapServiceReference.GetOrderStatusRequestDC OrderStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetOrderStatusRequestbyMerchantID", ReplyAction="http://tempuri.org/IPayGatewayService/GetOrderStatusRequestbyMerchantIDResponse")]
        System.Threading.Tasks.Task<WebAPI.TapServiceReference.OrderStatusResponseDC> GetOrderStatusRequestbyMerchantIDAsync(WebAPI.TapServiceReference.GetOrderStatusRequestDC OrderStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/CaptureAmount", ReplyAction="http://tempuri.org/IPayGatewayService/CaptureAmountResponse")]
        WebAPI.TapServiceReference.CaptureResponseDC CaptureAmount(WebAPI.TapServiceReference.CaptureRequestDC CaptureRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/CaptureAmount", ReplyAction="http://tempuri.org/IPayGatewayService/CaptureAmountResponse")]
        System.Threading.Tasks.Task<WebAPI.TapServiceReference.CaptureResponseDC> CaptureAmountAsync(WebAPI.TapServiceReference.CaptureRequestDC CaptureRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetOrderDetails", ReplyAction="http://tempuri.org/IPayGatewayService/GetOrderDetailsResponse")]
        WebAPI.TapServiceReference.OrderResponseDC GetOrderDetails(WebAPI.TapServiceReference.GetOrderRequestDC OrderRequestDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetOrderDetails", ReplyAction="http://tempuri.org/IPayGatewayService/GetOrderDetailsResponse")]
        System.Threading.Tasks.Task<WebAPI.TapServiceReference.OrderResponseDC> GetOrderDetailsAsync(WebAPI.TapServiceReference.GetOrderRequestDC OrderRequestDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/Refund", ReplyAction="http://tempuri.org/IPayGatewayService/RefundResponse")]
        WebAPI.TapServiceReference.RefundResponseDC Refund(WebAPI.TapServiceReference.RefundRequestDC RefundRequestDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/Refund", ReplyAction="http://tempuri.org/IPayGatewayService/RefundResponse")]
        System.Threading.Tasks.Task<WebAPI.TapServiceReference.RefundResponseDC> RefundAsync(WebAPI.TapServiceReference.RefundRequestDC RefundRequestDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetRefundStatus", ReplyAction="http://tempuri.org/IPayGatewayService/GetRefundStatusResponse")]
        WebAPI.TapServiceReference.RefundResponseDC GetRefundStatus(WebAPI.TapServiceReference.GetRefundStatusRequestDC GetRefundStatusRequestDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetRefundStatus", ReplyAction="http://tempuri.org/IPayGatewayService/GetRefundStatusResponse")]
        System.Threading.Tasks.Task<WebAPI.TapServiceReference.RefundResponseDC> GetRefundStatusAsync(WebAPI.TapServiceReference.GetRefundStatusRequestDC GetRefundStatusRequestDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetTransactions", ReplyAction="http://tempuri.org/IPayGatewayService/GetTransactionsResponse")]
        WebAPI.TapServiceReference.Transactions_Response GetTransactions(WebAPI.TapServiceReference.Transactions_Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayGatewayService/GetTransactions", ReplyAction="http://tempuri.org/IPayGatewayService/GetTransactionsResponse")]
        System.Threading.Tasks.Task<WebAPI.TapServiceReference.Transactions_Response> GetTransactionsAsync(WebAPI.TapServiceReference.Transactions_Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPayGatewayServiceChannel : WebAPI.TapServiceReference.IPayGatewayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PayGatewayServiceClient : System.ServiceModel.ClientBase<WebAPI.TapServiceReference.IPayGatewayService>, WebAPI.TapServiceReference.IPayGatewayService {
        
        public PayGatewayServiceClient() {
        }
        
        public PayGatewayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PayGatewayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayGatewayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayGatewayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAPI.TapServiceReference.PayResponseDC PaymentRequest(WebAPI.TapServiceReference.PayRequestDC PayRequest) {
            return base.Channel.PaymentRequest(PayRequest);
        }
        
        public System.Threading.Tasks.Task<WebAPI.TapServiceReference.PayResponseDC> PaymentRequestAsync(WebAPI.TapServiceReference.PayRequestDC PayRequest) {
            return base.Channel.PaymentRequestAsync(PayRequest);
        }
        
        public WebAPI.TapServiceReference.OrderStatusResponseDC GetOrderStatusRequest(WebAPI.TapServiceReference.GetOrderStatusRequestDC OrderStatusRequest) {
            return base.Channel.GetOrderStatusRequest(OrderStatusRequest);
        }
        
        public System.Threading.Tasks.Task<WebAPI.TapServiceReference.OrderStatusResponseDC> GetOrderStatusRequestAsync(WebAPI.TapServiceReference.GetOrderStatusRequestDC OrderStatusRequest) {
            return base.Channel.GetOrderStatusRequestAsync(OrderStatusRequest);
        }
        
        public WebAPI.TapServiceReference.OrderStatusResponseDC GetOrderStatusRequestbyMerchantID(WebAPI.TapServiceReference.GetOrderStatusRequestDC OrderStatusRequest) {
            return base.Channel.GetOrderStatusRequestbyMerchantID(OrderStatusRequest);
        }
        
        public System.Threading.Tasks.Task<WebAPI.TapServiceReference.OrderStatusResponseDC> GetOrderStatusRequestbyMerchantIDAsync(WebAPI.TapServiceReference.GetOrderStatusRequestDC OrderStatusRequest) {
            return base.Channel.GetOrderStatusRequestbyMerchantIDAsync(OrderStatusRequest);
        }
        
        public WebAPI.TapServiceReference.CaptureResponseDC CaptureAmount(WebAPI.TapServiceReference.CaptureRequestDC CaptureRequest) {
            return base.Channel.CaptureAmount(CaptureRequest);
        }
        
        public System.Threading.Tasks.Task<WebAPI.TapServiceReference.CaptureResponseDC> CaptureAmountAsync(WebAPI.TapServiceReference.CaptureRequestDC CaptureRequest) {
            return base.Channel.CaptureAmountAsync(CaptureRequest);
        }
        
        public WebAPI.TapServiceReference.OrderResponseDC GetOrderDetails(WebAPI.TapServiceReference.GetOrderRequestDC OrderRequestDC) {
            return base.Channel.GetOrderDetails(OrderRequestDC);
        }
        
        public System.Threading.Tasks.Task<WebAPI.TapServiceReference.OrderResponseDC> GetOrderDetailsAsync(WebAPI.TapServiceReference.GetOrderRequestDC OrderRequestDC) {
            return base.Channel.GetOrderDetailsAsync(OrderRequestDC);
        }
        
        public WebAPI.TapServiceReference.RefundResponseDC Refund(WebAPI.TapServiceReference.RefundRequestDC RefundRequestDC) {
            return base.Channel.Refund(RefundRequestDC);
        }
        
        public System.Threading.Tasks.Task<WebAPI.TapServiceReference.RefundResponseDC> RefundAsync(WebAPI.TapServiceReference.RefundRequestDC RefundRequestDC) {
            return base.Channel.RefundAsync(RefundRequestDC);
        }
        
        public WebAPI.TapServiceReference.RefundResponseDC GetRefundStatus(WebAPI.TapServiceReference.GetRefundStatusRequestDC GetRefundStatusRequestDC) {
            return base.Channel.GetRefundStatus(GetRefundStatusRequestDC);
        }
        
        public System.Threading.Tasks.Task<WebAPI.TapServiceReference.RefundResponseDC> GetRefundStatusAsync(WebAPI.TapServiceReference.GetRefundStatusRequestDC GetRefundStatusRequestDC) {
            return base.Channel.GetRefundStatusAsync(GetRefundStatusRequestDC);
        }
        
        public WebAPI.TapServiceReference.Transactions_Response GetTransactions(WebAPI.TapServiceReference.Transactions_Request request) {
            return base.Channel.GetTransactions(request);
        }
        
        public System.Threading.Tasks.Task<WebAPI.TapServiceReference.Transactions_Response> GetTransactionsAsync(WebAPI.TapServiceReference.Transactions_Request request) {
            return base.Channel.GetTransactionsAsync(request);
        }
    }
}
